unpackaged/main/default/objects/Document_Checklist_Item__c/Document_Checklist_Item__c.object-meta.xml
<CustomObject>
    <description>This custom object will have the information regarding the Document Checklist Items for IDB Invest Implemenatation.</description>
    <label>Document Checklist Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Checklist Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/IDB_Team_Role__c.field-meta.xml
<CustomField>
    <fullName>IDB_Team_Role__c</fullName>
    <label>Team Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Team Leader</fullName>
            </value>
            <value>
                <fullName>Investment Officer</fullName>
            </value>
            <value>
                <fullName>Financial Analyst / Alternate Investment Officer</fullName>
            </value>
            <value>
                <fullName>Financial Products and Services Officer</fullName>
            </value>
            <value>
                <fullName>Credit Risk Officer</fullName>
            </value>
            <value>
                <fullName>Environmental and Social Officer</fullName>
            </value>
            <value>
                <fullName>Transaction Attorney</fullName>
            </value>
            <value>
                <fullName>Development Effectiveness Officer</fullName>
            </value>
            <value>
                <fullName>Corporate Governance Officer</fullName>
            </value>
            <value>
                <fullName>Institutional Integrity Officer</fullName>
            </value>
            <value>
                <fullName>Resource Mobilization Officer</fullName>
            </value>
            <value>
                <fullName>Portfolio Management Officer</fullName>
            </value>
            <value>
                <fullName>Advisory Services Officer</fullName>
            </value>
            <value>
                <fullName>Special Assets Officer</fullName>
            </value>
            <value>
                <fullName>Alternate Portfolio Management Officer</fullName>
            </value>
            <value>
                <fullName>Loan Services Officer</fullName>
            </value>
            <value>
                <fullName>Alternate Special Assets Officer</fullName>
            </value>
            <value>
                <fullName>Portfolio Administration Officer</fullName>
            </value>
            <value>
                <fullName>Blended Finance Officer</fullName>
            </value>
            <value>
                <fullName>Loan Services Officer Monitoring</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Document Checklist Items</relationshipLabel>
    <relationshipName>Document_Checklist_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Template_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Template_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Initial Review</fullName>
        <default>true</default>
        <label>Initial Review</label>
    </customValue>
    <customValue>
        <fullName>Litigations Investigations Questionnaire</fullName>
    </customValue>
    <customValue>
        <fullName>Integrity Review</fullName>
    </customValue>
    <customValue>
        <fullName>Development Effectiveness</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate Governance</fullName>
    </customValue>
    <customValue>
        <fullName>Requirements for Environmental, Social and Occupational Health and Safety</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Information Requirements to Start the Environmental and Social Due Diligence Process</fullName>
    </customValue>
    <customValue>
        <fullName>Legal Due Diligence Questionnaire</fullName>
    </customValue>
    <customValue>
        <fullName>Legal Due Diligence Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Limited Legal Due Diligence Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Complete Legal Due Diligence</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Template Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/IDB_DataGenerator.cls
/**********************************************************************************************
* Name          : IDB_DataGenerator 
* Author        : Alejandro Ramirez
* Description   : Class to generate dummy data to use in test classes
* Created Date  : 16/04/2021
* Modification Log:
--------------------------------------------------------------------------------------------------------------
LastModifiedBy          | LastModifiedDate      | Modification Id   | Change description
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Alejandro Ramirez       | 16/04/2021            | v1.0              | First Class version Version
Alejandro Ramirez       | 19/05/2021            | v1.1              | Adding methods to generate dummy files
*********************************************************************************************/
public with sharing class IDB_DataGenerator {
    public static Account objAccount;
    public static Contact objContact;
    public static Opportunity objOpportunity;
    public static Document_Checklist_Item__c objDocCI;

    /* Method Name: createAccount
    * Author Name: Alejandro Ramirez
    * Description: Method to create dummy Account
    * Parameters: boolean isInsert
    * Returns: Account
    */
    public static Account createAccount(boolean isInsert) {
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Organization').getRecordTypeId();
        objAccount = new Account();
        objAccount.Name = 'Dummy Banco Agricola S.A. 10';
        objAccount.recordTypeId = recordTypeId;

        if(isInsert) {
            insert objAccount;
        }
        return objAccount; 
    }

    /* Method Name: createContact
    * Author Name: Alejandro Ramirez
    * Description: Method to create dummy Contact
    * Parameters: boolean isInsert
    * Returns: Contact
    */
    public static Contact createContact(boolean isInsert, Id accountIdIn) {
        Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        objContact = new Contact();
        objContact.FirstName = 'Dummy Max';
        objContact.LastName = 'Philiph';
        objContact.recordTypeId = recordTypeId;
        objContact.AccountId = (accountIdIn != null) ? accountIdIn : null;

        if(isInsert) {
            insert objContact;
        }
        return objContact; 
    }

    /* Method Name: createOpportunity
    * Author Name: Alejandro Ramirez
    * Description: Method to create dummy Opportunity
    * Parameters: boolean isInsert
    * Returns: Opportunity
    */
    public static Opportunity createOpportunity(boolean isInsert, Id contactIdIn) {
        Id recordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Opportunity (Wallet Share)').getRecordTypeId();
        objOpportunity = new Opportunity();
        objOpportunity.Name = 'Dummy Banco Agricola S.A. - TFFP (ES-L1031)';
        objOpportunity.recordTypeId = recordTypeId;
        objOpportunity.StageName = 'Initial Review';
        objOpportunity.CloseDate = System.today();
        objOpportunity.Primary_Contact__c = contactIdIn;

        if(isInsert) {
            insert objOpportunity;
        }
        return objOpportunity; 
    }

    /* Method Name: createDocumentChecklistItem
    * Author Name: Alejandro Ramirez
    * Description: Method to create dummy DocumentChecklistItem
    * Parameters: boolean isInsert
    * Returns: Document_Checklist_Item__c
    */
    public static Document_Checklist_Item__c createDocumentChecklistItem(boolean isInsert, Id opportunityIdIn) {
        Id recordTypeId = Schema.SObjectType.Document_Checklist_Item__c.getRecordTypeInfosByName().get('Documents').getRecordTypeId();
        objDocCI = new Document_Checklist_Item__c();
        objDocCI.Name = 'Dummy Insurance Policy';
        objDocCI.recordTypeId = recordTypeId;
        objDocCI.Opportunity__c = opportunityIdIn;
        objDocCI.Section__c = 'Initial Review';
        objDocCI.IDB_Team_Role__c = 'Team Leader';
        objDocCI.Status__c = 'Published';
        objDocCI.Description__c = 'Dummy Description';

        if(isInsert) {
            insert objDocCI;
        }
        return objDocCI; 
    }

    /* Method Name: createContentVersion
    * Author Name: Alejandro Ramirez
    * Description: Method to create dummy ContentVersion
    * Parameters: boolean isInsert, String strToConcat
    * Returns: ContentVersion
    */
    public static ContentVersion createContentVersion(boolean isInsert, String strToConcat) {
        ContentVersion objContentVersion = new ContentVersion(
            Title = 'Dummy Penguins ' + strToConcat,
            PathOnClient = 'DummyPenguins' + strToConcat + '.jpg',
            VersionData = Blob.valueOf('Test Content ' + strToConcat),
            IsMajorVersion = true
        );
        if(isInsert) {
            insert objContentVersion;
        }
        return objContentVersion;
    }

    /* Method Name: createContentDocumentLink
    * Author Name: Alejandro Ramirez
    * Description: Method to create dummy ContentVersion
    * Parameters: boolean isInsert, String strToConcat
    * Returns: ContentVersion
    */
    public static ContentDocumentLink createContentDocumentLink(boolean isInsert, Id linkedEntityId, Id contentDocumentId) {
        ContentDocumentLink objContentDocLink = New ContentDocumentLink();
        objContentDocLink.LinkedEntityId = linkedEntityId;
        objContentDocLink.ContentDocumentId = contentDocumentId;
        objContentDocLink.shareType = 'V';
        if(isInsert) {
            insert objContentDocLink;
        }
        return objContentDocLink;
    }

    /* Method Name: createOpportunityTeamMember
    * Author Name: Alejandro Ramirez
    * Description: Method to create dummy Opportunity team members
    * Parameters: boolean isInsert, Id oppId, Id usrId
    * Returns: OpportunityTeamMember
    */
    public static OpportunityTeamMember createOpportunityTeamMember(boolean isInsert, Id oppId, Id usrId) {
        OpportunityTeamMember objOTMtoReturn =  new OpportunityTeamMember();
        objOTMtoReturn.OpportunityId = oppId;
        objOTMtoReturn.UserId = usrId;
        objOTMtoReturn.TeamMemberRole = 'Team Leader';
        objOTMtoReturn.OpportunityAccessLevel = 'read'; 
        
        if(isInsert) {
            insert objOTMtoReturn;
        }
        return objOTMtoReturn;
    }

    /* Method Name: createDummyUser
    * Author Name: Alejandro Ramirez
    * Description: Method to create dummy Users
    * Parameters: boolean isInsert
    * Returns: User
    */
    public static User createDummyUser(boolean isInsert) {
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        Profile objProfile = [SELECT ID FROM Profile Where Name = 'IDB Invest Business Admin'];
        //[TimeZoneSidKey]
        User objDummyUser = new User(
            alias = 'dummTst',
            LastName = 'DummyTest',
            Username = uniqueName + '@test' + orgId + '.org',
            email = 'TstDmmy@test.com',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            TimeZoneSidKey = 'America/Chicago',
            ProfileId = objProfile.Id
        );
        if(isInsert) {
            insert objDummyUser;
        }
        return objDummyUser;
    }

    /* Method Name: createCustomDummyUser
    * Author Name: Alejandro Ramirez
    * Description: Method to create dummy Users
    * Parameters: boolean isInsert
    * Returns: User
    */
    public static User createCustomDummyUser(boolean isInsert, String strConcat) {
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        Profile objProfile = [SELECT ID FROM Profile Where Name = 'IDB Invest Business Admin'];
        //[TimeZoneSidKey]
        User objDummyUser = new User(
            alias = 'dumm' + strConcat,
            LastName = 'Dummy' + strConcat,
            Username = uniqueName + '@test' + orgId + '.org',
            email = 'Tst' +  + strConcat + 'Dmmy@test.com',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            TimeZoneSidKey = 'America/Chicago',
            ProfileId = objProfile.Id
        );
        if(isInsert) {
            insert objDummyUser;
        }
        return objDummyUser;
    }
}