unpackaged/main/default/objects/Document_Checklist_Item__c/Document_Checklist_Item__c.object-meta.xml
<CustomObject>
    <description>This custom object will have the information regarding the Document Checklist Items for IDB Invest Implemenatation.</description>
    <label>Document Checklist Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Checklist Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/IDB_Team_Role__c.field-meta.xml
<CustomField>
    <fullName>IDB_Team_Role__c</fullName>
    <label>Team Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Team Leader</fullName>
            </value>
            <value>
                <fullName>Investment Officer</fullName>
            </value>
            <value>
                <fullName>Financial Analyst / Alternate Investment Officer</fullName>
            </value>
            <value>
                <fullName>Financial Products and Services Officer</fullName>
            </value>
            <value>
                <fullName>Credit Risk Officer</fullName>
            </value>
            <value>
                <fullName>Environmental and Social Officer</fullName>
            </value>
            <value>
                <fullName>Transaction Attorney</fullName>
            </value>
            <value>
                <fullName>Development Effectiveness Officer</fullName>
            </value>
            <value>
                <fullName>Corporate Governance Officer</fullName>
            </value>
            <value>
                <fullName>Institutional Integrity Officer</fullName>
            </value>
            <value>
                <fullName>Resource Mobilization Officer</fullName>
            </value>
            <value>
                <fullName>Portfolio Management Officer</fullName>
            </value>
            <value>
                <fullName>Advisory Services Officer</fullName>
            </value>
            <value>
                <fullName>Special Assets Officer</fullName>
            </value>
            <value>
                <fullName>Alternate Portfolio Management Officer</fullName>
            </value>
            <value>
                <fullName>Loan Services Officer</fullName>
            </value>
            <value>
                <fullName>Alternate Special Assets Officer</fullName>
            </value>
            <value>
                <fullName>Portfolio Administration Officer</fullName>
            </value>
            <value>
                <fullName>Blended Finance Officer</fullName>
            </value>
            <value>
                <fullName>Loan Services Officer Monitoring</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Document Checklist Items</relationshipLabel>
    <relationshipName>Document_Checklist_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please, follow the structure's instructions:

Period &gt; Structure

Annual &gt; YYYY
Semester &gt; YYYY [1/2] H
Trimester	&gt; YYYY [1/2/3/4] Q
Monthly &gt; YYYY MM
Date &gt; YYYY MM DD
Date Range &gt;	[YYYY] – [YYYY] (Or specific dates range [YYYY MM DD])
No Date &gt; No Date</inlineHelpText>
    <label>Period</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Template_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Template_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Initial Review</fullName>
        <default>true</default>
        <label>Initial Review</label>
    </customValue>
    <customValue>
        <fullName>Litigations Investigations Questionnaire</fullName>
    </customValue>
    <customValue>
        <fullName>Integrity Review</fullName>
    </customValue>
    <customValue>
        <fullName>Development Effectiveness</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate Governance</fullName>
    </customValue>
    <customValue>
        <fullName>Requirements for Environmental, Social and Occupational Health and Safety</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Information Requirements to Start the Environmental and Social Due Diligence Process</fullName>
    </customValue>
    <customValue>
        <fullName>Legal Due Diligence Questionnaire</fullName>
    </customValue>
    <customValue>
        <fullName>Legal Due Diligence Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Limited Legal Due Diligence Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Complete Legal Due Diligence</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Template Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/IDB_ContentDocuLinkTriggerHandler_Test.cls
@isTest
private class IDB_ContentDocuLinkTriggerHandler_Test {
 @testSetup 
    static void setup(){
        
        //Inserting Contact  
        Contact newContact = new Contact();
        newContact.LastName = 'TestLastName';
        insert newContact;
        
        // Inserting Opportunity  
        Opportunity newOpportunity = new opportunity();
        newOpportunity.Name = 'TestOpportunity';
        newOpportunity.StageName = 'Initial Review';
        newOpportunity.CloseDate = System.today()+1;
        newOpportunity.Primary_Contact__c = newContact.Id;
        insert newOpportunity;
        
        // Inserting Opportunity Team        
         Id clientProfId = [SELECT Id FROM Profile WHERE Name='IDB Invest Team Lead' LIMIT 1].Id;
        User Usr = new User(LastName = 'Client User', Alias = 'Client', Email = 'test@test.com',Username = 'usertestinvest@iadbtest.com',
                            ProfileId = clientProfId,TimeZoneSidKey = 'GMT',LanguageLocaleKey = 'en_US',EmailEncodingKey = 'UTF-8',
                            LocaleSidKey = 'en_US'
                           );
        Insert Usr;
        
        OpportunityTeamMember oppTeam = new OpportunityTeamMember();
        oppTeam.OpportunityAccessLevel = 'Read';
        oppTeam.OpportunityId = newOpportunity.Id;
        oppTeam.UserId = Usr.Id;
        
        Insert oppTeam;
        
        // Inserting Document Checklist Item  
        Document_Checklist_Item__c newDCI = new Document_Checklist_Item__c();
        newDCI.Opportunity__c= newOpportunity.Id;
        newDCI.Description__c = 'Test Document Checklist Item';
        newDCI.Section__c= 'Initial Review';
        newDCI.Status__c= 'Approved';
        newDCI.IDB_Team_Role__c = 'Investment Officer';
        newDCI.Period__c = '2021';        
        insert newDCI;
    }
    
     static testmethod void validationRestrictionMethod(){
     
        User Usr = [SELECT Id FROM User WHERE Username='usertestinvest@iadbtest.com' LIMIT 1];
        System.runAs(Usr){
            Document_Checklist_Item__c newDCI = [SELECT Id FROM Document_Checklist_Item__c LIMIT 1];
            
            
               // Creating Content Document  
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        Insert cv;
        
        //Get Content Documents
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
        Approval.lock(newDCI.Id);
            Test.startTest();
            try{
        //Create ContentDocumentLink 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = newDCI.Id;
        cdl.ContentDocumentId = conDocId;
        //cdl.shareType = 'V';
        Insert cdl;
            }catch(Exception e){
                 Boolean expectedExceptionThrown =  e.getMessage().contains('File cannot be uploaded') ? true : false;
                System.assertEquals(expectedExceptionThrown, true);
            }
             Test.stopTest();
        }
     }
}