unpackaged/main/default/objects/Document_Checklist_Item__c/Document_Checklist_Item__c.object-meta.xml
<CustomObject>
    <description>This custom object will have the information regarding the Document Checklist Items for IDB Invest Implemenatation.</description>
    <label>Document Checklist Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Checklist Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/IDB_Next_Reminder_Date__c.field-meta.xml
<CustomField>
    <fullName>IDB_Next_Reminder_Date__c</fullName>
    <description>Field to set the next reminder date in order to send Approval notifications to approvers</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Next Reminder Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/IDB_Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>IDB_Submitted_Date__c</fullName>
    <description>Field to set the submitted date of a DCI</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Submitted Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Document Checklist Items</relationshipLabel>
    <relationshipName>Document_Checklist_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/IDB_SendApprovalDCIReminder_test.cls
/**********************************************************************************************
* Name          : IDB_SendApprovalDCIReminder_test 
* Author        : Alejandro Ramirez
* Description   : Test class for IDB_SendApprovalDCIReminder_batch
* Created Date  : 21/05/2021
* Modification Log:
--------------------------------------------------------------------------------------------------------------
LastModifiedBy          | LastModifiedDate      | Modification Id   | Change description
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Alejandro Ramirez       | 21/05/2021            | v1.0              | First Class version Version
*********************************************************************************************/
@isTest
public class IDB_SendApprovalDCIReminder_test {
    
    public static String CRON_EXP = '0 0 0 15 3 ? 2022';
    
    /* Method Name: makeData
    * Author Name: Alejandro Ramirez
    * Description: Method to generate dummy data
    * Parameters: None
    * Returns: NONE
    */
    @TestSetup
    private static void makeData() {
        /*Create account, create contact, create opportunity*/
        Account objAccount = IDB_DataGenerator.createAccount(true);
        Contact objContact = IDB_DataGenerator.createContact(true, objAccount.id);
        IDB_DataGenerator.createOpportunity(true, objContact.id);
    }

    /* Method Name: testSendApprovalDCIReminderBatch
    * Author Name: Alejandro Ramirez
    * Description: Method to test IDB_SendApprovalDCIReminder_batch.
    * Parameters: None
    * Returns: NONE
    */
    @isTest
    private static void testSendApprovalDCIReminderBatch() {
        Opportunity objDummyOpportunity = [SELECT id, Name, StageName, CloseDate FROM Opportunity WHERE Name LIKE '%Dummy%' LIMIT 1];
        System.assertNotEquals(null, objDummyOpportunity);
        Document_Checklist_Item__c objDummyDCI = IDB_DataGenerator.createDocumentChecklistItem(false, objDummyOpportunity.Id);
		objDummyDCI.Status__c = 'Submitted';
        objDummyDCI.IDB_Next_Reminder_Date__c = System.today();
        objDummyDCI.IDB_Submitted_Date__c = System.today();
        insert objDummyDCI;
        Document_Checklist_Item__c objDummyDCI2 = IDB_DataGenerator.createDocumentChecklistItem(false, objDummyOpportunity.Id);
        objDummyDCI2.Name = 'Dummy Insurance Policy 2';
        objDummyDCI2.Status__c = 'Submitted';
        objDummyDCI2.IDB_Next_Reminder_Date__c = System.today();
        objDummyDCI2.IDB_Submitted_Date__c = System.today();
        insert objDummyDCI2;
        
        Test.startTest();
            IDB_SendApprovalDCIReminder_batch objSendAppReminderBatch = new IDB_SendApprovalDCIReminder_batch();
            Database.executeBatch(objSendAppReminderBatch);
		Test.stopTest();
        System.AssertEquals(
           database.countquery('SELECT COUNT()'
              +' FROM Document_Checklist_Item__c WHERE Opportunity__c = \'' + objDummyOpportunity.Id + '\''),
           2); 
	}

    /* Method Name: testSendApprovalDCIReminderSch
    * Author Name: Alejandro Ramirez
    * Description: Method to test IDB_SendApprovalDCIReminder_sch.
    * Parameters: None
    * Returns: NONE
    */
    @isTest
    private static void testSendApprovalDCIReminderSch() {
        Opportunity objDummyOpportunity = [SELECT id, Name, StageName, CloseDate FROM Opportunity WHERE Name LIKE '%Dummy%' LIMIT 1];
        System.assertNotEquals(null, objDummyOpportunity);
        Document_Checklist_Item__c objDummyDCI = IDB_DataGenerator.createDocumentChecklistItem(false, objDummyOpportunity.Id);
		objDummyDCI.Status__c = 'Submitted';
        objDummyDCI.IDB_Next_Reminder_Date__c = System.today();
        objDummyDCI.IDB_Submitted_Date__c = System.today();
        insert objDummyDCI;
        Document_Checklist_Item__c objDummyDCI2 = IDB_DataGenerator.createDocumentChecklistItem(false, objDummyOpportunity.Id);
        objDummyDCI2.Name = 'Dummy Insurance Policy 2';
        objDummyDCI2.Status__c = 'Submitted';
        objDummyDCI2.IDB_Next_Reminder_Date__c = System.today();
        objDummyDCI2.IDB_Submitted_Date__c = System.today();
        insert objDummyDCI2;
        
        Test.startTest();
            System.schedule('SendApprovalDCIReminderSchTest',
            CRON_EXP,
            new IDB_SendApprovalDCIReminder_sch());
		Test.stopTest();

        System.AssertEquals(
           database.countquery('SELECT COUNT()'
              +' FROM Document_Checklist_Item__c WHERE Opportunity__c = \'' + objDummyOpportunity.Id + '\''),
           2); 
	}
}