unpackaged/main/default/objects/Document_Checklist_Item__c/Document_Checklist_Item__c.object-meta.xml
<CustomObject>
    <description>This custom object will have the information regarding the Document Checklist Items for IDB Invest Implemenatation.</description>
    <label>Document Checklist Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Checklist Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/ATI_Exception__c.field-meta.xml
<CustomField>
    <fullName>ATI_Exception__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ATI Exception</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/Contains_PII__c.field-meta.xml
<CustomField>
    <fullName>Contains_PII__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contains PII?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Document Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Function</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/IDB_EzShare_Number_Ext__c.field-meta.xml
<CustomField>
    <fullName>IDB_EzShare_Number_Ext__c</fullName>
    <description>This field is used for EzShare Documents</description>
    <encryptionScheme>None</encryptionScheme>
    <label>EzShare Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/IDB_Link__c.field-meta.xml
<CustomField>
    <fullName>IDB_Link__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Link</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/IDB_Subsection__c.field-meta.xml
<CustomField>
    <fullName>IDB_Subsection__c</fullName>
    <label>Subsection</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Section__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>IDB_Subsection</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/IDB_Survey__c.field-meta.xml
<CustomField>
    <fullName>IDB_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey</referenceTo>
    <relationshipName>Document_Checklist_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/IDB_Team_Role__c.field-meta.xml
<CustomField>
    <fullName>IDB_Team_Role__c</fullName>
    <label>Team Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Team Leader</fullName>
            </value>
            <value>
                <fullName>Investment Officer</fullName>
            </value>
            <value>
                <fullName>Financial Analyst / Alternate Investment Officer</fullName>
            </value>
            <value>
                <fullName>Financial Products and Services Officer</fullName>
            </value>
            <value>
                <fullName>Credit Risk Officer</fullName>
            </value>
            <value>
                <fullName>Environmental and Social Officer</fullName>
            </value>
            <value>
                <fullName>Transaction Attorney</fullName>
            </value>
            <value>
                <fullName>Development Effectiveness Officer</fullName>
            </value>
            <value>
                <fullName>Corporate Governance Officer</fullName>
            </value>
            <value>
                <fullName>Institutional Integrity Officer</fullName>
            </value>
            <value>
                <fullName>Resource Mobilization Officer</fullName>
            </value>
            <value>
                <fullName>Portfolio Management Officer</fullName>
            </value>
            <value>
                <fullName>Advisory Services Officer</fullName>
            </value>
            <value>
                <fullName>Special Assets Officer</fullName>
            </value>
            <value>
                <fullName>Alternate Portfolio Management Officer</fullName>
            </value>
            <value>
                <fullName>Loan Services Officer</fullName>
            </value>
            <value>
                <fullName>Alternate Special Assets Officer</fullName>
            </value>
            <value>
                <fullName>Portfolio Administration Officer</fullName>
            </value>
            <value>
                <fullName>Blended Finance Officer</fullName>
            </value>
            <value>
                <fullName>Loan Services Officer Monitoring</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/Instructions__c.field-meta.xml
<CustomField>
    <fullName>Instructions__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Instructions</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/List_Name__c.field-meta.xml
<CustomField>
    <fullName>List_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>List Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Document Checklist Items</relationshipLabel>
    <relationshipName>Document_Checklist_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/Record_Access_Classification_IIC__c.field-meta.xml
<CustomField>
    <fullName>Record_Access_Classification_IIC__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Record Access Classification IIC</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Template_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Document_Checklist_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Template_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Initial Review</fullName>
        <default>true</default>
        <label>Initial Review</label>
    </customValue>
    <customValue>
        <fullName>Litigations Investigations Questionnaire</fullName>
    </customValue>
    <customValue>
        <fullName>Integrity Review</fullName>
    </customValue>
    <customValue>
        <fullName>Development Effectiveness</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate Governance</fullName>
    </customValue>
    <customValue>
        <fullName>Requirements for Environmental, Social and Occupational Health and Safety</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Information Requirements to Start the Environmental and Social Due Diligence Process</fullName>
    </customValue>
    <customValue>
        <fullName>Legal Due Diligence Questionnaire</fullName>
    </customValue>
    <customValue>
        <fullName>Legal Due Diligence Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Limited Legal Due Diligence Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Complete Legal Due Diligence</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Template Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/IDB_DocumentChecklist_CC.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* IDB_DocumentChecklist_CC class created for creating Document Checklist Items on Opportunity
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Vivek Kasireddy  <vivek.kasireddy@capgemini.com>
* @modifiedBy     Vivek Kasireddy  <vivek.kasireddy@capgemini.com>
* @maintainedBy   Vivek Kasireddy  <vivek.kasireddy@capgemini.com>
* @version        1.0
* @created        2020-10-23
* @modified       2021-01-06
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/

public with sharing class IDB_DocumentChecklist_CC{
    
    /**
* ───────────────────────────────────────────────────────────────────────────────────────────────┐
* fetchDocumentChecklistTemplates method created for fetching Published Document Checklist Template records
* ────────────────────────────────────────────────────────────────────────────────────────────────
* @param    NO PARAM
* @return   List<Document_Checklist_Template__c>
* ───────────────────────────────────────────────────────────────────────────────────────────────┘
*/
    @AuraEnabled
    public static List<Document_Checklist_Template__c> fetchDocumentChecklistTemplates(){
        List<Document_Checklist_Template__c> dctRecords = new List<Document_Checklist_Template__c>();
        dctRecords =    [SELECT Id,Name,Template_Name__c
                         FROM Document_Checklist_Template__c
                         WHERE Status__c =: System.label.Published_Status
                         WITH SECURITY_ENFORCED
                         ORDER BY Name
                        ];
        return dctRecords;
    }
    
    /**
* ───────────────────────────────────────────────────────────────────────────────────────────────┐
* fetchDocumentChecklistTemplateItem method created for fetching Document Checklist Template Item records
* ────────────────────────────────────────────────────────────────────────────────────────────────
* @param    String
* @return   List<Document_Checklist_Template_Item__c>
* ───────────────────────────────────────────────────────────────────────────────────────────────┘
*/
    
    @AuraEnabled
    public static Map<String,List<Document_Checklist_Template_Item__c>> fetchDocumentChecklistTemplateItem(String templateId){
        List<Document_Checklist_Template_Item__c> dctiRecords = new List<Document_Checklist_Template_Item__c>();
        Map<String,List<Document_Checklist_Template_Item__c>> sectionGroupMap = new Map<String,List<Document_Checklist_Template_Item__c>>();
        if(String.isNotBlank(templateId)){
            dctiRecords =   [SELECT Id,Name,Description__c,Section__c
                             FROM Document_Checklist_Template_Item__c
                             WHERE Template__c =: templateId
                             WITH SECURITY_ENFORCED
                             ORDER BY Section__c
                            ];
            
            for(Document_Checklist_Template_Item__c eachDCTI : dctiRecords){
                List<Document_Checklist_Template_Item__c> dcti = new List<Document_Checklist_Template_Item__c>();
                dcti.add(eachDCTI);
                if(sectionGroupMap.containsKey(eachDCTI.Section__c)){
                    dcti.addAll(sectionGroupMap.get(eachDCTI.Section__c));
                    sectionGroupMap.put(eachDCTI.Section__c,dcti);
                }else{
                    sectionGroupMap.put(eachDCTI.Section__c,dcti);
                }
            }
        }
        return sectionGroupMap;
    }
    
    /**
* ───────────────────────────────────────────────────────────────────────────────────────────────┐
* createDocumentChecklistItems method created for creating Document Checklist Item records
* ────────────────────────────────────────────────────────────────────────────────────────────────
* @param    String
* @param    List<String>
* @return   VOID
* ───────────────────────────────────────────────────────────────────────────────────────────────┘
*/
    
    @AuraEnabled
    public static void createDocumentChecklistItems(String opportunityId, List<String> documentChecklistTemplateItemIds){
        List<Document_Checklist_Template_Item__c> dctiRecords = new List<Document_Checklist_Template_Item__c> ();
        if(String.isNotBlank(opportunityId) && !documentChecklistTemplateItemIds.isEmpty()){
            dctiRecords =    [SELECT Id, Name, RecordTypeId, Contains_PII__c,ListName__c, Function__c, Activity__c, Record_Access_Classification_IIC__c,ATI_Exception__c,Document_Type__c, Instructions__c, IDB_Link__c, Description__c, IDB_Survey__c, Template__c, Section__c, IDB_Subsection__c,IDB_Team_Role__c,IDB_EzShare_Number_Ext__c
                              FROM Document_Checklist_Template_Item__c
                              WHERE Id IN : documentChecklistTemplateItemIds
                              WITH SECURITY_ENFORCED
                              ORDER BY Name
                             ];
            
            String jsonData = JSON.serialize(dctiRecords);
            System.debug('JsonData-' + jsonData);
        }
        List<Document_Checklist_Item__c> dciRecords = new List<Document_Checklist_Item__c>();
        if(!dctiRecords.isEmpty()){
            for(Document_Checklist_Template_Item__c eachDCTIRecord : dctiRecords){
                Document_Checklist_Item__c dciRecord = new Document_Checklist_Item__c();
                dciRecord.RecordTypeId = IDB_Utility.getRecordTypeIdbyName(System.label.DocumentChecklistItem,IDB_Utility.getRecordTypeNameById(System.label.DocumentChecklistTemplateItem,eachDCTIRecord.RecordTypeId));
                dciRecord.Name = eachDCTIRecord.Name;
                dciRecord.Contains_PII__c = eachDCTIRecord.Contains_PII__c;
                dciRecord.Instructions__c = eachDCTIRecord.Instructions__c;
                dciRecord.IDB_Link__c = eachDCTIRecord.IDB_Link__c;
                dciRecord.Description__c = eachDCTIRecord.Description__c;
                dciRecord.Opportunity__c = opportunityId;
                dciRecord.Status__c = System.label.New_Status;
                dciRecord.IDB_Survey__c = eachDCTIRecord.IDB_Survey__c;
                dciRecord.Section__c = eachDCTIRecord.Section__c;
                dciRecord.IDB_Subsection__c = eachDCTIRecord.IDB_Subsection__c;
                dciRecord.IDB_Team_Role__c = eachDCTIRecord.IDB_Team_Role__c;
                dciRecord.IDB_EzShare_Number_Ext__c = eachDCTIRecord.IDB_EzShare_Number_Ext__c;
                dciRecord.List_Name__c = eachDCTIRecord.ListName__c;
                dciRecord.Function__c = eachDCTIRecord.Function__c;
                dciRecord.Activity__c = eachDCTIRecord.Activity__c;
                dciRecord.Record_Access_Classification_IIC__c = eachDCTIRecord.Record_Access_Classification_IIC__c;
                dciRecord.ATI_Exception__c = eachDCTIRecord.ATI_Exception__c;
                dciRecord.Document_Type__c = eachDCTIRecord.Document_Type__c;                                
                dciRecords.add(dciRecord);
            }
        }
        if(!dciRecords.isEmpty()){
            try{
                Database.insert(dciRecords,true);
            }catch(Exception exp){
                system.debug('exp = '+exp);
            }   
        }
    }
    
    
}